### ISSUE TITLE
Support built_value model

### ISSUE THREAD

**Issue by dfdgsdfg** [Fidev-io/framy#117]
[built_value](https://pub.dev/packages/built_value)is similar to Freezed but created by google.

It is used widely Dart and Flutter ecosystem.

 If Framy supports it, it would be great. 😄

**Comment by MarcinusX** [comment]
Hey!
Thanks for pointing it out!

I agree. We should definitely support it!

**Comment by MarcinusX** [comment]
@dfdgsdfg Could you confirm that it's working for you in generator version 0.1.7? :)
