### ISSUE TITLE
Allow custom screens

### ISSUE THREAD

**Issue by MarcinusX** [Fidev-io/framy#9]
I believe that adding a Flag "isPage" or "isScreen" will be enough :D

**Comment by nateshmbhat** [comment]
to distinguish between screens and non screen widgets , why not put a @framyScreen annotation ?

**Comment by nateshmbhat** [comment]
this can help with segregating screens from normal widgets which can be used for a lot of new features and use cases ( say for example , grouping all screens in a single view and allowing the user to explore a particular screen).

**Comment by MarcinusX** [comment]
You got it right. :)
The thought about both another annotation and bool parameter, at this moment it's easier to do the latter but from implementation pov, it shouldn't be hard to switch if needed.

**Comment by nateshmbhat** [comment]
I think it's better to have an annotation because who knows what kind of features or flags u might be adding in future that are specific to a screen ?

If you provide a is Screen flag, then u can't add more options in future that are specific to screen inside this framy widget annotation.

**Comment by MarcinusX** [comment]
Actually, it got resolved by #127 already. Although we will keep an eye on that and we will add separate annotation if needed.
